# Generated by Django 6.0.6 on 2026-06-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teammembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('leader', 'Leader'), ('member', 'Normal'), ('read_only', 'Read_Only'), ('restricted', 'Restricted')], default='member', max_length=20),
        ),
    ]
