# Generated by Django 6.0.6 on 2026-06-18 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('tickets', '0005_remove_ticket_assignees_ticket_assigned_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_team__isnull', True), ('assigned_user__isnull', False)), models.Q(('assigned_team__isnull', False), ('assigned_user__isnull', True)), _connector='OR'), name='ticket_exactly_one_assignment'),
        ),
    ]
