# Generated by Django 6.0.6 on 2026-06-18 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_ticket_exactly_one_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtickets', to='tickets.ticket'),
        ),
    ]
