# Generated by Django 6.0.6 on 2026-06-19 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='actual_time',
            field=models.PositiveIntegerField(blank=True, help_text='Actual time to complete, in minutes.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time to complete, in minutes.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
