# Generated by Django 6.0.6 on 2026-06-19 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_actual_time_ticket_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estimated_time',
            field=models.PositiveIntegerField(help_text='Estimated time to complete, in minutes.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
