# Generated by Django 6.0.6 on 2026-06-19 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_estimated_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('commit', 'Commit'), ('pull_request', 'Pull Request'), ('merge_request', 'Merge Request'), ('changeset', 'Changeset'), ('custom', 'Custom')], default='commit', max_length=32)),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('azure_devops', 'Azure DevOps'), ('custom', 'Custom')], default='manual', max_length=32)),
                ('external_id', models.CharField(help_text='Commit hash, PR number, changelist ID, or external reference ID.', max_length=255)),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='tickets.ticket')),
            ],
        ),
    ]
