# Generated by Django 6.0.6 on 2026-06-19 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teammembership_role'),
        ('tickets', '0010_ticketreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTicketPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_reference_on_close', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_policy', to='teams.team')),
            ],
        ),
    ]
