# Generated by Django 6.0.6 on 2026-06-19 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teammembership_role'),
        ('tickets', '0012_ticketevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('teams', 'Microsoft Teams'), ('webhook', 'Generic Webhook'), ('whatsapp', 'WhatsApp')], max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('webhook_url', models.URLField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='tickets.notificationchannel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='tickets.ticketevent')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ticket.created', 'Ticket created'), ('ticket.updated', 'Ticket updated'), ('ticket.status_changed', 'Status changed'), ('ticket.assigned', 'Ticket assigned'), ('ticket.closed', 'Ticket closed'), ('ticket.reopened', 'Ticket reopened'), ('ticket.reference_added', 'Reference added')], max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tickets.notificationchannel')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='teams.team')),
            ],
        ),
    ]
