# Generated by Django 6.0.6 on 2026-06-19 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teammembership_role'),
        ('tickets', '0013_notificationchannel_notificationdelivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_prefix', models.CharField(help_text='Short prefix used to identify the token without storing the raw token.', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_tokens', to='teams.team')),
            ],
        ),
    ]
